# Generated by Django 4.2.13 on 2024-07-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customername', models.CharField(max_length=100)),
                ('billingaddr', models.CharField(max_length=100)),
                ('shippingaddr', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=100)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryname', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoiceheader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviewapp.invoiceheader')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoicerelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewapp.invoiceheader')),
            ],
        ),
    ]
