# Generated by Django 4.2.13 on 2024-07-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesundry',
            name='invoiceheader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewapp.invoiceheader'),
        ),
    ]
